---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project
spec:
  selector:
    app: capstone-project
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
...
