---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment-1aa940fd-79db-4e9a-9954-ca60c5b021c8
spec:
  selector:
    matchLabels:
      app: capstone-project-1aa940fd-79db-4e9a-9954-ca60c5b021c8
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: capstone-project-1aa940fd-79db-4e9a-9954-ca60c5b021c8
        tier: backend
        track: stable
    spec:
      containers:
      - name: capstone-project
        image: "judt/udacity-cloud-devops-engineer-capstone-project:1aa940fd-79db-4e9a-9954-ca60c5b021c8"
        envFrom:
        - secretRef:
            name: database-access
        ports:
          - name: http
            containerPort: 8000
...
