Description: >
  RDS for Postgres database including security group. Udacity Cloud DevOps Engineer - Capstone Project

Parameters:
  MyDBInstanceIdentifier:
    Description: Name for the DB instance
    Type: String
  MyDBSnapshotIdentifier:
    Description: Name or ARN of the DB snapshot to restore
    Type: String
  DBPort:
    Description: Port of the DB for application connections
    Type: String
  DBUsername:
    Description: Any username
    Type: String
  DBPassword:
    Description: A password with at least 8 characters
    Type: String
  MyVpcId:
    Description: Id of the VPC to use for the security group
    Type: String

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to the database
      GroupName: !Sub ${MyDBInstanceIdentifier}-postgres
      VpcId: !Sub "${MyVpcId}"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: !Sub "${DBPort}"
        ToPort: !Sub "${DBPort}"
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: Udacity Capstone Project

  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: postgres
      DBInstanceIdentifier: !Sub "${MyDBInstanceIdentifier}"
      DBSnapshotIdentifier: !Sub "${MyDBSnapshotIdentifier}"
      Port: !Sub "${DBPort}"
      PubliclyAccessible: true
      MultiAZ: false
      AllocatedStorage: 20
      StorageType: gp2
      DBInstanceClass: db.t3.micro
      # Use default VPC and Subnet for DB
      VPCSecurityGroups:
      - !Ref DBSecurityGroup
      MasterUsername: !Sub "${DBUsername}"
      MasterUserPassword: !Sub "${DBPassword}"
      Tags:
      - Key: Name
        Value: Udacity Capstone Project
    DeletionPolicy: "Snapshot"
