apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::880754027086:role/eksNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::880754027086:user/Udacity
      username: eksadmin
      groups:
        - system:masters
    - userarn: arn:aws:iam::880754027086:user/Udacity-circleci
      username: eksadmin
      groups:
        - system:masters
