Description: >
  Elastic Kubernetes Service for backend, Udacity Cloud DevOps Engineer - Capstone Project

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String
  SubnetID1:
    Description: Subnet identifier 1 for EKS nodes.
    Type: String
  SubnetID2:
    Description: Subnet identifier 2 for EKS nodes.
    Type: String
  SubnetID3:
    Description: Subnet identifier 3 for EKS nodes.
    Type: String

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "cluster-${WorkflowID}"
      RoleArn: arn:aws:iam::880754027086:role/eksClusterRole
      ResourcesVpcConfig:
        EndpointPublicAccess: true
        EndpointPrivateAccess: false
        SubnetIds:
        - !Sub "${SubnetID1}"
        - !Sub "${SubnetID2}"
        - !Sub "${SubnetID3}"
      Tags:
      - Key: Name
        Value: Udacity Capstone Project

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      NodegroupName: !Sub "cluster-nodegroup-${WorkflowID}"
      ClusterName: !Ref EKSCluster
      NodeRole: arn:aws:iam::880754027086:role/eksNodeRole
      AmiType: AL2_x86_64
      InstanceTypes:
      - t2.micro
      ScalingConfig:
        DesiredSize: 4
        MinSize: 4
        MaxSize: 6
      Subnets:
      - !Sub "${SubnetID1}"
      - !Sub "${SubnetID2}"
      - !Sub "${SubnetID3}"
      Tags:
        Name: Udacity Capstone Project

Outputs:
  K8sAPIEndpoint:
    Value: !GetAtt EKSCluster.Endpoint
    Description: Endpoint of the K8s API server
